version: '3.8'

services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /opt/app/.tmp/data.db
      JWT_SECRET: tobechanged
      ADMIN_JWT_SECRET: tobechanged
      APP_KEYS: tobechanged
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads